"""Initial schema

Revision ID: 6812ce80c660
Revises: 
Create Date: 2026-09-04 14:04:19.478638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6812ce80c660'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('from_domain', sa.String(length=255), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('prob_legitimate', sa.Float(), nullable=False),
    sa.Column('prob_spam', sa.Float(), nullable=False),
    sa.Column('prob_phishing', sa.Float(), nullable=False),
    sa.Column('bert_contribution', sa.Float(), nullable=False),
    sa.Column('url_contribution', sa.Float(), nullable=False),
    sa.Column('header_contribution', sa.Float(), nullable=False),
    sa.Column('sender_contribution', sa.Float(), nullable=False),
    sa.Column('keyword_contribution', sa.Float(), nullable=False),
    sa.Column('spf_pass', sa.Boolean(), nullable=False),
    sa.Column('dkim_pass', sa.Boolean(), nullable=False),
    sa.Column('dmarc_pass', sa.Boolean(), nullable=False),
    sa.Column('urls_found', sa.Integer(), nullable=False),
    sa.Column('malicious_url_count', sa.Integer(), nullable=False),
    sa.Column('newly_reg_domain_count', sa.Integer(), nullable=False),
    sa.Column('flagged_keywords', sa.Text(), nullable=True),
    sa.Column('explain_method', sa.String(length=100), nullable=False),
    sa.Column('explain_summary', sa.Text(), nullable=True),
    sa.Column('total_latency_ms', sa.Float(), nullable=False),
    sa.Column('bert_latency_ms', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_classification'), 'analyses', ['classification'], unique=False)
    op.create_index(op.f('ix_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_analyses_email_hash'), 'analyses', ['email_hash'], unique=False)
    op.create_index(op.f('ix_analyses_from_domain'), 'analyses', ['from_domain'], unique=False)
    op.create_index(op.f('ix_analyses_risk_score'), 'analyses', ['risk_score'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('macro_f1', sa.Float(), nullable=False),
    sa.Column('roc_auc', sa.Float(), nullable=False),
    sa.Column('p50_latency_ms', sa.Float(), nullable=False),
    sa.Column('train_samples', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index(op.f('ix_model_versions_is_active'), 'model_versions', ['is_active'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('correct_label', sa.String(length=20), nullable=False),
    sa.Column('model_was_wrong', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_analysis_id'), 'feedback', ['analysis_id'], unique=False)
    op.create_table('url_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('is_malicious', sa.Boolean(), nullable=False),
    sa.Column('is_newly_registered', sa.Boolean(), nullable=False),
    sa.Column('domain_age_days', sa.Integer(), nullable=True),
    sa.Column('uses_ip_address', sa.Boolean(), nullable=False),
    sa.Column('has_suspicious_tld', sa.Boolean(), nullable=False),
    sa.Column('is_typosquat', sa.Boolean(), nullable=False),
    sa.Column('typosquat_target', sa.String(length=100), nullable=True),
    sa.Column('redirect_count', sa.Integer(), nullable=False),
    sa.Column('virustotal_hits', sa.Integer(), nullable=False),
    sa.Column('google_safebrowsing_flagged', sa.Boolean(), nullable=False),
    sa.Column('flags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_results_analysis_id'), 'url_results', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_url_results_domain'), 'url_results', ['domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_results_domain'), table_name='url_results')
    op.drop_index(op.f('ix_url_results_analysis_id'), table_name='url_results')
    op.drop_table('url_results')
    op.drop_index(op.f('ix_feedback_analysis_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_model_versions_is_active'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_analyses_risk_score'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_from_domain'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_email_hash'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_created_at'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_classification'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
